import os
import re

def markdown_to_latex(text, is_course=False):
    # Regex for headers (avoid double numbering)
    # Remove # 1. Title or ## A. Title formats to let LaTeX handle it
    text = re.sub(r'^#\s+(?:[0-9]+\.|[A-Z]\.)?\s*(.*?)$', r'\\section*{\1}', text, flags=re.MULTILINE)
    if is_course:
        text = re.sub(r'^##\s+(?:[0-9]+\.|[A-Z]\.)?\s*(.*?)$', r'\\section{\1}', text, flags=re.MULTILINE)
        text = re.sub(r'^###\s+(?:[0-9]+\.|[A-Z]\.)?\s*(.*?)$', r'\\subsection{\1}', text, flags=re.MULTILINE)
    else:
        text = re.sub(r'^##\s+(?:[0-9]+\.|[A-Z]\.)?\s*(.*?)$', r'\\subsection*{\1}', text, flags=re.MULTILINE)
        text = re.sub(r'^###\s+(?:[0-9]+\.|[A-Z]\.)?\s*(.*?)$', r'\\subsubsection*{\1}', text, flags=re.MULTILINE)

    # Tokenize text and math/code blocks to safely replace ** and *
    tokens = re.split(r'(\$\$.*?\$\$|\$.*?\$|\\begin\{lstlisting\}.*?\\end\{lstlisting\}|\\begin\{tikzpicture\}.*?\\end\{tikzpicture\}|\\begin\{center\}.*?\\end\{center\})', text, flags=re.DOTALL)

    for i in range(len(tokens)):
        if i % 2 == 0:  # Standard text
            # Replace bold
            tokens[i] = re.sub(r'\*\*(.*?)\*\*', r'\\textbf{\1}', tokens[i])
            # Replace italic, taking care not to mess up math if it slipped
            tokens[i] = re.sub(r'\b\*(.*?)\*\b', r'\\textit{\1}', tokens[i])

            # Blockquotes
            tokens[i] = re.sub(r'^>\s*(.*?)$', r'\\begin{quote}\1\\end{quote}', tokens[i], flags=re.MULTILINE)
            # Combine adjacent blockquotes
            tokens[i] = re.sub(r'\\end\{quote\}\s*\\begin\{quote\}', ' ', tokens[i], flags=re.DOTALL)

            # Escape unescaped ampersands
            tokens[i] = re.sub(r'(?<!\\)&', r'\&', tokens[i])

    return "".join(tokens)

def main():
    course_path = "jalon-82/Jalon-82.md"
    tex_path = "jalon-82/jalon-82.tex"

    with open(course_path, 'r', encoding='utf-8') as f:
        course_md = f.read()

    # Remove YAML frontmatter
    course_md = re.sub(r'^---.*?---\n', '', course_md, flags=re.DOTALL)

    latex_doc = r"""\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[french]{babel}
\usepackage{amsmath,amssymb,amsthm}
\usepackage{geometry}
\geometry{hmargin=2.5cm,vmargin=3cm}
\usepackage{tikz}
\usetikzlibrary{cd,positioning,shapes}
\usepackage{listings}
\usepackage{xcolor}

\lstset{
    language=Python,
    basicstyle=\ttfamily\small,
    keywordstyle=\color{blue}\bfseries,
    stringstyle=\color{red},
    commentstyle=\color{gray}\itshape,
    numbers=left,
    numberstyle=\tiny\color{gray},
    breaklines=true,
    frame=single,
    showstringspaces=false
}

\title{\Huge INTRODUCTION AUX DISTRIBUTIONS DE SCHWARTZ \\ \large Cours magistral, exercices corrigés et travaux pratiques}
\author{\Large Charles EDOU NZE}
\date{\today}

\begin{document}
\maketitle
\tableofcontents
\newpage

\part{Cours Magistral}
"""

    latex_doc += markdown_to_latex(course_md, is_course=True)

    latex_doc += "\n\\newpage\n\\part{Exercices d'Application et de Concours}\n"

    # Add exercises
    for i in range(1, 11):
        exo_path = f"jalon-82/exos/Exo-{i:02d}.md"
        with open(exo_path, 'r', encoding='utf-8') as f:
            exo_md = f.read()
            latex_doc += markdown_to_latex(exo_md, is_course=False) + "\n\n"

    latex_doc += "\n\\newpage\n\\part{Travaux Pratiques et Simulations Algorithmiques}\n"

    # Add TPs
    for i in range(1, 6):
        tp_path = f"jalon-82/tp/TP-{i:02d}.md"
        with open(tp_path, 'r', encoding='utf-8') as f:
            tp_md = f.read()
            # TPs already have LaTeX headers generated by tmp_tps.py, so don't convert them again.
            latex_doc += tp_md + "\n\n"

    latex_doc += "\\end{document}\n"

    # Fix the \section*{# Jalon 82...} that might have been created
    latex_doc = re.sub(r'\\section\*\{\#\s*', r'\\section*{', latex_doc)

    with open(tex_path, 'w', encoding='utf-8') as f:
        f.write(latex_doc)

if __name__ == "__main__":
    main()
