import os
import glob
import time
import sys
import re
from google import genai
from google.genai import types

# Récupération sécurisée du client Gemini API
client = genai.Client(api_key=os.environ.get("GOOGLE_API_KEY"))

# Le modèle recommandé pour un équilibre entre rapidité, fenêtres de contexte et qualité
MODEL_ID = 'gemini-2.5-flash'

# Pre-compile regular expressions for performance
RE_YEAR = re.compile(r'\*\*Année\s+(\d+).*?\*\*')
RE_TRIM = re.compile(r'\*\*Trimestre\s+(\d+).*?\*\*')
RE_PREV = re.compile(r'\*\*Précédent\*\*\s*:\s*\[\[(.*?)\]\]')
RE_NEXT = re.compile(r'\*\*Suivant\*\*\s*:\s*\[\[(.*?)\]\]')
RE_TITLE_CLEAN_PARENS = re.compile(r'Jalon(s)? [\d à]+ \((.*?)\)')
RE_TITLE_CLEAN_PREFIX = re.compile(r'^Jalon(s)? [\d à]+\s*:?\s*')
RE_TITLE_CLEAN_FILE = re.compile(r'^Jalon(s)? [\d à]+ \((.*?)\)\.md$')
RE_JALON_NUM = re.compile(r'Jalon(s)? ([\d à]+)')

TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), 'prompt_template.txt')
PROMPT_TEMPLATE = None

def get_prompt_template():
    global PROMPT_TEMPLATE
    if PROMPT_TEMPLATE is None:
        with open(TEMPLATE_PATH, "r", encoding="utf-8") as template_file:
            PROMPT_TEMPLATE = template_file.read()
    return PROMPT_TEMPLATE

def get_jalon_files():
    # Trouve tous les fichiers de Jalons dans les sous-dossiers
    files = glob.glob("Jalon*/**/*.md", recursive=True)
    # Filter to ensure we only get the main jalon files if needed, 
    # but based on the move, they are the only ones for now.
    return sorted(files)

def extract_metadata(content):
    year = "1"
    trimester = "1"
    prev_link = ""
    next_link = ""

    # Parse metadata from current file content generated by generate_jalons.py
    # Typical header:
    # # Jalon X
    # **Année Y** > **Trimestre Z**

    match_year = RE_YEAR.search(content)
    if match_year:
        year = match_year.group(1)

    match_trim = RE_TRIM.search(content)
    if match_trim:
        trimester = match_trim.group(1)

    match_prev = RE_PREV.search(content)
    if match_prev:
        prev_link = f'"[[{match_prev.group(1)}.md]]"'

    match_next = RE_NEXT.search(content)
    if match_next:
        next_link = f'"[[{match_next.group(1)}.md]]"'

    return year, trimester, prev_link, next_link

def extract_main_content(content):
    # Check if the first part is YAML frontmatter (for existing enrichments)
    parts = content.split('---\n')
    if len(parts) > 1:
        main_content = "---\n".join(parts[:-1]).strip()

        nav_links = parts[-1].strip()
        if not ("**Précédent**" in nav_links or "**Suivant**" in nav_links):
            main_content = content
    else:
        main_content = content

    return main_content

def extract_clean_title(main_content, filepath):
    lines = main_content.split('\n')
    title = lines[0].replace('# ', '') if lines and lines[0].startswith('# ') else os.path.basename(filepath).replace('.md', '')

    # Nettoyage rapide du titre pour le prompt
    title_clean = RE_TITLE_CLEAN_PARENS.sub(r'\2', title)
    # also remove the 'Jalon X' prefix if any
    title_clean = RE_TITLE_CLEAN_PREFIX.sub('', title_clean)
    title_clean = title_clean.strip()

    # Sometimes title contains original mojibake if not properly parsed, so use clean fallback
    clean_filename_title = RE_TITLE_CLEAN_FILE.sub(r'\2', os.path.basename(filepath))

    if not title_clean or title_clean == os.path.basename(filepath).replace('.md', ''):
        title_clean = clean_filename_title

    return title_clean

def parse_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    year, trimester, prev_link, next_link = extract_metadata(content)
    main_content = extract_main_content(content)
    title_clean = extract_clean_title(main_content, filepath)

    return main_content, title_clean, year, trimester, prev_link, next_link

def generate_enriched_content(title, original_content, filepath, year, trimester, prev_link, next_link):
    # Extraction du numéro de jalon depuis le nom du fichier pour le YAML
    match_num = RE_JALON_NUM.search(os.path.basename(filepath))
    jalon_num = match_num.group(2) if match_num else "0"
    # normalize for uuid
    jalon_num_clean = jalon_num.replace(" à ", "-").strip()

    prev_yaml = f'\nprev: {prev_link}' if prev_link else ''
    next_yaml = f'\nnext: {next_link}' if next_link else ''

    # Load the prompt template from an external file to keep the code clean
    template = get_prompt_template()

    prompt = template.format(
        title=title,
        jalon_num=jalon_num,
        original_content=original_content,
        jalon_num_clean=jalon_num_clean,
        year=year,
        trimester=trimester,
        prev_yaml=prev_yaml,
        next_yaml=next_yaml
    )

    max_retries = 10
    retry_delay = 60

    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model=MODEL_ID,
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=0.3, # Température basse pour maximiser la rigueur mathématique
                )
            )
            return response.text
        except Exception as e:
            error_msg = str(e)
            if "RESOURCE_EXHAUSTED" in error_msg or "429" in error_msg or "exceeded your current quota" in error_msg:
                print(f"Limite d'API atteinte (Rate Limit). Attente de {retry_delay}s... (Essai {attempt+1}/{max_retries})")
                sys.stdout.flush()
                time.sleep(retry_delay)
            else:
                print(f"Erreur lors de la génération de contenu pour {title}: {e}")
                return None

    print(f"Échec après {max_retries} tentatives pour le jalon {title}.")
    return None

def main():
    if not os.environ.get("GOOGLE_API_KEY"):
        print("Erreur: La variable d'environnement GOOGLE_API_KEY n'est pas définie.")
        sys.exit(1)

    print("Démarrage du processus d'enrichissement...")
    sys.stdout.flush()
    files = get_jalon_files()
    print(f"{len(files)} fichiers trouvés.")
    sys.stdout.flush()

    for i, filepath in enumerate(files):
        print(f"Traitement {i+1}/{len(files)}: {filepath}")
        sys.stdout.flush()

        original_content, title, year, trimester, prev_link, next_link = parse_file(filepath)

        # On vérifie si le fichier possède déjà la nouvelle structure YAML complète pour éviter de le refaire
        # (Si year, trimester et uuid sont là, on suppose que c'est bon)
        first_lines = "".join(original_content.splitlines(True)[:10])
        if "uuid: \"jalon-" in first_lines and "year:" in first_lines and "trimester:" in first_lines and "## 1. Présentation du concept clé" in original_content:
            print(f"  -> Le fichier {filepath} possède déjà la nouvelle structure. Ignoré.")
            sys.stdout.flush()
            continue

        enriched_text = generate_enriched_content(title, original_content, filepath, year, trimester, prev_link, next_link)

        if enriched_text:
            # Nettoyage des balises de code Markdown parasites si le modèle en ajoute
            clean_text = enriched_text
            if clean_text.startswith("```markdown"):
                clean_text = clean_text[11:]
            if clean_text.endswith("```"):
                clean_text = clean_text[:-3]
            clean_text = clean_text.strip()

            new_content = clean_text + "\n"

            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(new_content)

            print(f"  -> Succès: fichier enrichi et sauvegardé {filepath}")
        else:
            print(f"  -> Échec: impossible d'enrichir {filepath}")
        sys.stdout.flush()

        # Modération des requêtes pour préserver le quota standard
        time.sleep(5)

    print("Processus d'enrichissement terminé avec succès.")

if __name__ == "__main__":
    main()
